// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOUS-nYG2e8RN0ANYWprmsd8P6Gsdb2J8',
    appId: '1:860190259558:web:0a3539e9fb70381e4770a7',
    messagingSenderId: '860190259558',
    projectId: 'merit-ai-804dd',
    authDomain: 'merit-ai-804dd.firebaseapp.com',
    storageBucket: 'merit-ai-804dd.firebasestorage.app',
    measurementId: 'G-7NJ6PKE84F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_A-sI7ytt60ldAxL4Xi_3-N_R8HWp2Fg',
    appId: '1:860190259558:android:758481705b6ac7c24770a7',
    messagingSenderId: '860190259558',
    projectId: 'merit-ai-804dd',
    storageBucket: 'merit-ai-804dd.firebasestorage.app',
  );
}
